[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Joseph Gallant", email = "115753611+joseph-d-gallant@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "argon2-cffi>=25.1.0",
    "fastapi>=0.141.1",
    "psycopg[binary,pool]>=3.3.6",
    "pyjwt>=2.15.0",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.53.0",
]

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
