class UserNotFoundError(Exception): ...


class UserAlreadyExistsError(Exception): ...


class PasswordAlreadyExistsError(Exception): ...


class PasswordDeletionError(Exception): ...


class PasswordNotCachedError(Exception): ...


class AuthenticationError(Exception): ...


class SessionIsExpiredError(Exception): ...


class EmptyVaultError(Exception): ...
